#:import style gui.style
<StackLayoutedNodeBodyBase>
    size_hint: None, None
    canvas.before:
        Color:
            rgb: style.node_body_background_color
        RoundedRectangle:
            pos: self.pos
            size: self.size
            radius: [(0, 0), (0, 0), (10, 10), (10, 10)]

    height: sum([c.height + dp(5) for c in self.children]) + dp(15)
    padding: dp(15)
    spacing: dp(5)