<GetParamsNodeBody>
    width: dp(170)
    height: dp(85)
    InputField:
        height: dp(10)
        size_hint: 1, None
        id: regression_input
        label_text: 'regression input'
    LabeledCheckBox:
        label_text: 'deep'
        is_checked: root.deep
        on_is_checked: root.deep = args[1]
    OutputField:
        height: dp(20)
        size_hint: 1, None
        id: output
        label_italic: True
        label_text: 'output'